name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/caddy-dynu:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
