name: Build caddy-dynu

on:
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry (GHCR) using a PAT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username of the authenticated user
          password: ${{ secrets.GHCR_PAT }}  # Use the PAT for authentication
          registry: ghcr.io  # Specify GitHub Container Registry (GHCR)

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/caddy-dynu:${{ github.sha }} .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/caddy-dynu:${{ github.sha }}
          # Optionally, you can also tag the image with a version (e.g., a tag or `latest`)
          docker tag ghcr.io/${{ github.repository_owner }}/caddy-dynu:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/caddy-dynu:latest
          docker push ghcr.io/${{ github.repository_owner }}/caddy-dynu:latest
